name: CI/CD

on:
  push:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt
      - run: flake8 .
      - run: pytest

  deploy:
    needs: test   # 👈 only run if test passes
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: List Railway services
        run: railway status
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Deploy to Railway
        run: railway up --service cicd
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}